In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("C:\\Users\\DELL\\Desktop\\CAPSTONE PROJECT 10\\online_shoppers_intention.csv")

In [3]:
df2=df.copy()

In [4]:
df2=pd.get_dummies(data=df, columns=['Month', 'VisitorType'])
df2.head(5)

Administrative  Administrative_Duration  Informational  \
0               0                      0.0              0   
1               0                      0.0              0   
2               0                      0.0              0   
3               0                      0.0              0   
4               0                      0.0              0   

   Informational_Duration  ProductRelated  ProductRelated_Duration  \
0                     0.0               1                 0.000000   
1                     0.0               2                64.000000   
2                     0.0               1                 0.000000   
3                     0.0               2                 2.666667   
4                     0.0              10               627.500000   

   BounceRates  ExitRates  PageValues  SpecialDay  ...  Month_Jul  Month_June  \
0         0.20       0.20         0.0         0.0  ...          0           0   
1         0.00       0.10         0.0         0.0  ...          0           0   
2         0.20       0.20         0.0         0.0  ...          0           0   
3         0.05       0.14         0.0         0.0  ...          0           0   
4         0.02       0.05         0.0         0.0  ...          0           0   

   Month_Mar  Month_May  Month_Nov  Month_Oct  Month_Sep  \
0          0          0          0          0          0   
1          0          0          0          0          0   
2          0          0          0          0          0   
3          0          0          0          0          0   
4          0          0          0          0          0   

   VisitorType_New_Visitor  VisitorType_Other  VisitorType_Returning_Visitor  
0                        0                  0                              1  
1                        0                  0                              1  
2                        0                  0                              1  
3                        0                  0                              1  
4                        0                  0                              1  

[5 rows x 29 columns]

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [6]:
df2.columns

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'Weekend',
       'Revenue', 'Month_Aug', 'Month_Dec', 'Month_Feb', 'Month_Jul',
       'Month_June', 'Month_Mar', 'Month_May', 'Month_Nov', 'Month_Oct',
       'Month_Sep', 'VisitorType_New_Visitor', 'VisitorType_Other',
       'VisitorType_Returning_Visitor'],
      dtype='object')

In [ ]:
#Logistic Regression

In [7]:
X = df2.drop(['Revenue'],axis=1)

# Putting response variable to y
y = df2['Revenue']

In [8]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [9]:
model = LogisticRegression()

In [10]:
model.fit(x_train, y_train)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [11]:
y_test_predicted = model.predict(x_test)
y_test_predicted

array([False, False, False, ..., False, False, False])

In [12]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_test_predicted)
confusion_matrix

array([[3003,   74],
       [ 387,  235]], dtype=int64)

In [13]:
from sklearn.metrics import accuracy_score
accuracy_score = accuracy_score(y_test, y_test_predicted)
accuracy_score

0.8753717220870506

In [14]:
from sklearn.metrics import classification_report

In [15]:
print(classification_report(y_test, y_test_predicted, target_names=['Yes', 'No']))

              precision    recall  f1-score   support

         Yes       0.89      0.98      0.93      3077
          No       0.76      0.38      0.50       622

    accuracy                           0.88      3699
   macro avg       0.82      0.68      0.72      3699
weighted avg       0.86      0.88      0.86      3699



In [ ]:
#Decision Tree

In [16]:
from sklearn.tree import DecisionTreeClassifier

In [17]:
model=DecisionTreeClassifier(criterion = 'gini',max_depth=4)
model.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [18]:
ypred2=model.predict(x_test)


In [19]:
from sklearn import metrics

In [20]:
acc=metrics.accuracy_score(y_test,ypred2)
print(acc)

0.8905109489051095


In [21]:
cm2=metrics.confusion_matrix(y_test,ypred2)
print(cm2)

[[2947  130]
 [ 275  347]]


In [22]:
cr2=metrics.classification_report(y_test,ypred2)
print(cr2)

              precision    recall  f1-score   support

       False       0.91      0.96      0.94      3077
        True       0.73      0.56      0.63       622

    accuracy                           0.89      3699
   macro avg       0.82      0.76      0.78      3699
weighted avg       0.88      0.89      0.88      3699



In [ ]:
#GaussianNB

In [23]:
from sklearn.naive_bayes import GaussianNB

In [24]:
model = GaussianNB()
model.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [25]:
# make predictions
expected = y_test
ypred3 = model.predict(x_test)
# summarize the fit of the model
print(metrics.classification_report(expected, ypred3))
print(metrics.confusion_matrix(expected, ypred3))

              precision    recall  f1-score   support

       False       0.91      0.83      0.87      3077
        True       0.42      0.62      0.50       622

    accuracy                           0.79      3699
   macro avg       0.67      0.72      0.68      3699
weighted avg       0.83      0.79      0.81      3699

[[2540  537]
 [ 239  383]]


In [26]:
acc=metrics.accuracy_score(y_test,ypred3)
print(acc)

0.7902135712354691


In [27]:
predicted_proba = model.predict_proba(x_test)

In [28]:
predicted_proba

array([[8.86138001e-01, 1.13861999e-01],
       [2.51067536e-04, 9.99748932e-01],
       [6.28362419e-01, 3.71637581e-01],
       ...,
       [9.91723693e-01, 8.27630698e-03],
       [9.92547274e-01, 7.45272602e-03],
       [9.70854015e-01, 2.91459848e-02]])

In [ ]:
#BernoulliNB

In [29]:
from sklearn.naive_bayes import BernoulliNB, MultinomialNB

In [30]:
model1=BernoulliNB()
model1.fit(x_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [31]:
expected = y_test
y_pred4 = model1.predict(x_test)
y_pred_proba = model1.predict(x_test)
# summarize the fit of the model
print(metrics.classification_report(expected, y_pred4))
print(metrics.confusion_matrix(expected, y_pred4))

              precision    recall  f1-score   support

       False       0.91      0.90      0.91      3077
        True       0.54      0.56      0.55       622

    accuracy                           0.84      3699
   macro avg       0.72      0.73      0.73      3699
weighted avg       0.85      0.84      0.85      3699

[[2778  299]
 [ 275  347]]


In [32]:
print(metrics.accuracy_score(y_test,y_pred4))

0.8448229251148959


In [ ]:
#MultiNomiaNB

In [33]:
mnb = MultinomialNB()

In [34]:
mnb.fit(x_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [35]:
expected = y_test
ypred5 = mnb.predict(x_test)
# summarize the fit of the model
print(metrics.classification_report(expected, ypred5))
print(metrics.confusion_matrix(expected, ypred5))

              precision    recall  f1-score   support

       False       0.92      0.92      0.92      3077
        True       0.60      0.59      0.59       622

    accuracy                           0.86      3699
   macro avg       0.76      0.75      0.75      3699
weighted avg       0.86      0.86      0.86      3699

[[2828  249]
 [ 256  366]]


In [36]:
print(metrics.accuracy_score(y_test,ypred5))

0.8634766153014328


In [ ]:
#Scaling

In [37]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [38]:
scaler=StandardScaler()

In [39]:
scaled_data=scaler.fit_transform(df2)

#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

In [40]:
df2.head()

Administrative  Administrative_Duration  Informational  \
0               0                      0.0              0   
1               0                      0.0              0   
2               0                      0.0              0   
3               0                      0.0              0   
4               0                      0.0              0   

   Informational_Duration  ProductRelated  ProductRelated_Duration  \
0                     0.0               1                 0.000000   
1                     0.0               2                64.000000   
2                     0.0               1                 0.000000   
3                     0.0               2                 2.666667   
4                     0.0              10               627.500000   

   BounceRates  ExitRates  PageValues  SpecialDay  ...  Month_Jul  Month_June  \
0         0.20       0.20         0.0         0.0  ...          0           0   
1         0.00       0.10         0.0         0.0  ...          0           0   
2         0.20       0.20         0.0         0.0  ...          0           0   
3         0.05       0.14         0.0         0.0  ...          0           0   
4         0.02       0.05         0.0         0.0  ...          0           0   

   Month_Mar  Month_May  Month_Nov  Month_Oct  Month_Sep  \
0          0          0          0          0          0   
1          0          0          0          0          0   
2          0          0          0          0          0   
3          0          0          0          0          0   
4          0          0          0          0          0   

   VisitorType_New_Visitor  VisitorType_Other  VisitorType_Returning_Visitor  
0                        0                  0                              1  
1                        0                  0                              1  
2                        0                  0                              1  
3                        0                  0                              1  
4                        0                  0                              1  

[5 rows x 29 columns]

In [54]:
def Models(x_train,y_train,x_test,y_test):
    
    x_train=x_train
    y_train=y_train
    x_test=x_test
    y_test=y_test

    from sklearn.linear_model import LogisticRegression
    from sklearn.model_selection import train_test_split
    from sklearn.metrics import confusion_matrix
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import classification_report
    from sklearn.tree import DecisionTreeClassifier
    from sklearn import metrics
    from sklearn.naive_bayes import GaussianNB
    from sklearn.naive_bayes import BernoulliNB, MultinomialNB


    
    print("LOGISTIC REGRESSION")
    lg = LogisticRegression()
    lg.fit(x_train, y_train)
    ypred = lg.predict(x_test)
    confusion_matrix = confusion_matrix(y_test, ypred)
    print("Confusion matrix for Logistic:",confusion_matrix)
    accuracy_score = accuracy_score(y_test, ypred)
    print("Accuracy score for Logistic:",accuracy_score)
    print("Classification Report for Logistic report",classification_report(y_test, ypred, target_names=['Yes', 'No']))

    print("DECISION TREE")
    dt=DecisionTreeClassifier(criterion = 'gini',max_depth=4)
    dt.fit(x_train,y_train)
    ypred2=dt.predict(x_test)
    cm2=metrics.confusion_matrix(y_test,ypred2)
    print("Confusion matrix for Decision Tree:",cm2)
    acc2=metrics.accuracy_score(y_test,ypred2)
    print("Accuracy score for Decision Tree:",acc2)
    cr2=metrics.classification_report(y_test,ypred2)
    print("Classification Report for Logistic report",cr2)

    print("Naive Bayes Gaussian")
    gnb = GaussianNB()
    gnb.fit(x_train, y_train)
    ypred3=gnb.predict(x_test)
    cm3=metrics.confusion_matrix(y_test,ypred3)
    print("Confusion matrix for Gaussian:",cm3)
    acc3=metrics.accuracy_score(y_test,ypred3)
    print("Accuracy score for Gaussian:",acc3)
    cr3=metrics.classification_report(y_test,ypred3)
    print("Classification Report for Gaussian",cr3)

    print("Naive Bayes Bernoulli")
    bnb = BernoulliNB()
    bnb.fit(x_train, y_train)
    ypred4=bnb.predict(x_test)
    cm4=metrics.confusion_matrix(y_test,ypred4)
    print("Confusion matrix for Bernoulli",cm4)
    acc4=metrics.accuracy_score(y_test,ypred4)
    print("Accuracy score for Bernoulli:",acc4)
    cr4=metrics.classification_report(y_test,ypred4)
    print("Classification Report for Bernoulli:",cr4)

    print("Naive Bayes Multinomial")
    mnb = MultinomialNB()
    mnb.fit(x_train, y_train)
    ypred5=mnb.predict(x_test)
    cm5=metrics.confusion_matrix(y_test,ypred5)
    print("Confusion matrix for Multinomial:",cm5)
    acc=metrics.accuracy_score(y_test,ypred5)
    print("Accuracy score for Multinomial:",acc)
    cr5=metrics.classification_report(y_test,ypred5)
    print("Classification Report for Multinomial:",cr5)
    
    return

In [ ]:
#Models applied on scaled data

In [42]:
X = df2.drop(['Revenue'],axis=1)

# Putting response variable to y
y = df2['Revenue']
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [43]:
Models(x_train,y_train,x_test,y_test)

LOGISTIC REGRESSION


C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Confusion matrix for Logistic: [[3003   74]
 [ 387  235]]
Accuracy score for Logistic: 0.8753717220870506
Classification Report for Logistic report               precision    recall  f1-score   support

         Yes       0.89      0.98      0.93      3077
          No       0.76      0.38      0.50       622

    accuracy                           0.88      3699
   macro avg       0.82      0.68      0.72      3699
weighted avg       0.86      0.88      0.86      3699

DECISION TREE
Confusion matrix for Decision Tree: [[2947  130]
 [ 275  347]]
Accuracy score for Decision Tree: 0.8905109489051095
Classification Report for Logistic report               precision    recall  f1-score   support

       False       0.91      0.96      0.94      3077
        True       0.73      0.56      0.63       622

    accuracy                           0.89      3699
   macro avg       0.82      0.76      0.78      3699
weighted avg       0.88      0.89      0.88      3699

Naive Bayes Gaussian
Confu

In [ ]:
#oversampling

In [44]:
pip install imblearn

Note: you may need to restart the kernel to use updated packages.


In [45]:
from imblearn.over_sampling import SMOTE

In [46]:
y_train.value_counts()

False    7345
True     1286
Name: Revenue, dtype: int64

In [47]:
smt=SMOTE()
x_train,y_train=smt.fit_sample(x_train,y_train)

In [48]:
np.bincount(y_train)

array([7345, 7345], dtype=int64)

In [49]:
x_test,y_test=smt.fit_sample(x_test,y_test)

In [50]:
np.bincount(y_test)

array([3077, 3077], dtype=int64)

In [ ]:
#Models applied on oversampled data

In [51]:
Models(x_train,y_train,x_test,y_test)

LOGISTIC REGRESSION


C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Confusion matrix for Logistic: [[2718  359]
 [ 692 2385]]
Accuracy score for Logistic: 0.8292167695807605
Classification Report for Logistic report               precision    recall  f1-score   support

         Yes       0.80      0.88      0.84      3077
          No       0.87      0.78      0.82      3077

    accuracy                           0.83      6154
   macro avg       0.83      0.83      0.83      6154
weighted avg       0.83      0.83      0.83      6154

DECISION TREE
Confusion matrix for Decision Tree: [[2779  298]
 [ 251 2826]]
Accuracy score for Decision Tree: 0.9107897302567436
Classification Report for Logistic report               precision    recall  f1-score   support

       False       0.92      0.90      0.91      3077
        True       0.90      0.92      0.91      3077

    accuracy                           0.91      6154
   macro avg       0.91      0.91      0.91      6154
weighted avg       0.91      0.91      0.91      6154

Naive Bayes Gaussian
Confu

In [53]:
df2.columns

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'Weekend',
       'Revenue', 'Month_Aug', 'Month_Dec', 'Month_Feb', 'Month_Jul',
       'Month_June', 'Month_Mar', 'Month_May', 'Month_Nov', 'Month_Oct',
       'Month_Sep', 'VisitorType_New_Visitor', 'VisitorType_Other',
       'VisitorType_Returning_Visitor'],
      dtype='object')

In [ ]:
#Variance Inflation factor

In [55]:
import statsmodels.api                      as     sm
import scipy.stats                          as     stats
from   patsy                                import dmatrices
from   statsmodels.stats.outliers_influence import variance_inflation_factor

In [57]:
features ="Administrative + Administrative_Duration + Informational + Informational_Duration + ProductRelated + ProductRelated_Duration + BounceRates + ExitRates + PageValues + SpecialDay + OperatingSystems + Browser + Region  + TrafficType + Weekend + Month_Aug  +  Month_Dec + Month_Feb + Month_Jul + Month_June + Month_Mar + Month_May + Month_Nov + Month_Oct + Month_Sep + VisitorType_New_Visitor + VisitorType_Other + VisitorType_Returning_Visitor"
y, X = dmatrices('Revenue ~' + features, df2, return_type='dataframe')

In [58]:
vif               = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif["features"]   = X.columns
print(vif)

C:\Users\DELL\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1543: RuntimeWarning: divide by zero encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
C:\Users\DELL\Anaconda3\lib\site-packages\statsmodels\stats\outliers_influence.py:181: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)


    VIF Factor                       features
0     0.000000                      Intercept
1     1.012325                Weekend[T.True]
2     1.959938                 Administrative
3     1.692911        Administrative_Duration
4     1.835911                  Informational
5     1.681260         Informational_Duration
6     4.502195                 ProductRelated
7     4.348421        ProductRelated_Duration
8     6.414579                    BounceRates
9     7.164583                      ExitRates
10    1.058246                     PageValues
11    1.332347                     SpecialDay
12    1.172725               OperatingSystems
13    1.143916                        Browser
14    1.026887                         Region
15    1.089245                    TrafficType
16         inf                      Month_Aug
17         inf                      Month_Dec
18         inf                      Month_Feb
19         inf                      Month_Jul
20         inf                    

In [ ]:
#Feature Reduction-RFE using Logistic

In [59]:
from sklearn.feature_selection import RFE

In [52]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

#on 15 features
lg1 = LogisticRegression()

rfe = RFE(lg1, 15)
rfe = rfe.fit(x_train, y_train)
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

[False False False False False False  True  True  True  True False False
 False False False  True  True  True  True False  True  True  True False
  True  True  True  True]
[ 7 12  2 13 10 14  1  1  1  1  5  6  8 11  9  1  1  1  1  4  1  1  1  3
  1  1  1  1]


In [64]:
logg = LogisticRegression()
rfe = RFE(logg, 9) #on 9 features
fit = rfe.fit(X, y)
print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_))
print("Feature Ranking: %s" % (fit.ranking_))

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

Num Features: 9
Selected Features: [False False False False False False  True  True False  True False False
 False False False  True False  True False False False False  True  True
  True False False  True]
Feature Ranking: [14 19  7 17 16 20  1  1 11  1 12 13 15 18  9  1  5  1  2  4  3  8  1  1
  1  6 10  1]


In [81]:
X = df2.drop(['Revenue'],axis=1)

# Putting response variable to y
y = df2['Revenue']

In [63]:
df2.columns

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'Weekend',
       'Revenue', 'Month_Aug', 'Month_Dec', 'Month_Feb', 'Month_Jul',
       'Month_June', 'Month_Mar', 'Month_May', 'Month_Nov', 'Month_Oct',
       'Month_Sep', 'VisitorType_New_Visitor', 'VisitorType_Other',
       'VisitorType_Returning_Visitor'],
      dtype='object')

Important features as Per RFE: 'BounceRates', 'ExitRates','SpecialDay','Month_Feb','Month_Sep','Month_Nov', 'Month_Oct','VisitorType_Returning_Visitor'

In [ ]:
#DecisionTree RFE

In [82]:
dt1 = DecisionTreeClassifier(criterion = 'gini',max_depth=4)
rfe = RFE(dt1,9 ) #on 9 features
fit = rfe.fit(X, y)
print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_))
print("Feature Ranking: %s" % (fit.ranking_))

Num Features: 9
Selected Features: [ True False False False  True  True  True  True  True False False False
 False False False False False False False False False False  True False
  True  True False False]
Feature Ranking: [ 1  8  7  6  1  1  1  1  1 12 14 16 18 20 19 17 15 13 11  5  4  3  1  2
  1  1  9 10]


In [ ]:
#RidgeRegression

In [65]:
from sklearn.linear_model import Ridge

In [66]:
ridge = Ridge(alpha=1.0)
ridge.fit(X,y)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [67]:
def pretty_print_coefs(coefs, names = None, sort = False):
    if names == None:
        names = ["X%s" % x for x in range(len(coefs))]
    lst = zip(coefs, names)
    if sort:
        lst = sorted(lst,  key = lambda x:-np.abs(x[0]))
    return " + ".join("%s * %s" % (round(coef, 3), name)
                                   for coef, name in lst)

In [68]:
print ("Ridge model:", pretty_print_coefs(ridge.coef_))

Ridge model: 0.002 * X0 + -0.0 * X1 + 0.003 * X2 + 0.0 * X3 + 0.0 * X4 + 0.0 * X5 + 0.256 * X6 + -0.772 * X7 + 0.009 * X8 + -0.018 * X9 + -0.008 * X10 + 0.004 * X11 + -0.002 * X12 + -0.0 * X13 + 0.008 * X14 + 0.016 * X15 + -0.034 * X16 + -0.045 * X17 + 0.018 * X18 + -0.018 * X19 + -0.023 * X20 + -0.024 * X21 + 0.078 * X22 + 0.02 * X23 + 0.011 * X24 + 0.04 * X25 + -0.031 * X26 + -0.01 * X27


In [85]:
X = df2.ix[:, (0, 4, 5,6, 7, 8,22,24,25)]
y = df2.ix[:, 15]

C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


In [ ]:
#baggingclassifier

In [86]:
my_model=LogisticRegression()
my_model2=DecisionTreeClassifier(criterion='gini',max_depth=4)
my_model3=GaussianNB()

In [87]:
from sklearn.ensemble import BaggingClassifier
#Default base estimator is Decision Tree (CART)

bgcl = BaggingClassifier(base_estimator=my_model2,n_estimators=51,oob_score=True)
bgcl.fit(X,y)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None,
                                                        criterion='gini',
                                                        max_depth=4,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort=False,
                                                        random_state=None,
                                                        splitter='best'),
       

In [88]:
bgcl.oob_score_

0.8980535279805353

In [89]:
y_pred = bgcl.predict(x_test)
y_pred

array([False, False, False, ..., False, False, False])

In [90]:
acc=metrics.accuracy_score(y_test,y_pred)
acc*100

89.29440389294405

In [91]:
cr=metrics.classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

       False       0.91      0.96      0.94      3077
        True       0.76      0.54      0.63       622

    accuracy                           0.89      3699
   macro avg       0.83      0.75      0.78      3699
weighted avg       0.89      0.89      0.89      3699



In [92]:
cm=metrics.confusion_matrix(y_test,y_pred)
print(cm)

[[2969  108]
 [ 288  334]]
